name: CI of mc_naoqi_dcm with Docker

# This workflow checks the build-and-install script on base docker images

on:
  push:
    paths-ignore:
      # Changes to those files don't mandate running CI
      - ".gitlab-ci.yml"
      - ".jrl-ci"
      - ".github/workflows/package.yml"
      - "debian/**"
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu_20.04"]
        robot: ["nao", "pepper"] # robot
        version: ["2.5.0", "2.1.4"] # ctc toolchain version
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Build with Docker (${{matrix.robot}} (ctc-toolchain version - ${{matrix.version}})
      run: |
        echo "Starting docker build for ${{matrix.robot}} (ctc-toolchain version - ${{matrix.version}})"
        ./docker/build.sh ${{matrix.robot}} ${{matrix.version}}
    - name: Upload library as artefact (${{matrix.robot}} (ctc-toolchain version - ${{matrix.version}})
      uses: actions/upload-artifact@master
      with:
        name: libmc_naoqi_dcm_${{matrix.robot}}_${{matrix.version}}.so
        path: /tmp/libmc_naoqi_dcm_${{matrix.robot}}_${{matrix.version}}.so
